chore: adds shauna to README and updates documentation to reflect usage of all-contributors CLI
trussworks/react-uswds pull request #2194
Opened 2022-09-21 16:45 UTC by Shkeating

# Summary

Re-does adding myself to the contributors file, and improves documentation to prevent similar mistakes from future contributors. In this branch I did three things:

- removes my manually added code from the README file to prevent issues with the CLI tool moving forward
- adds myself using the CLI tool
- updates the `For Trussels` file to instruct new people to use the tool so they don't make the same mistake I did 😅

## Related Issues or PRs

https://github.com/trussworks/react-uswds/pull/2193 - where I added myself manually 

## How To Test

- check if I show up in the README preview
- Review the text I wrote in the `for-trussels.md` file. open to suggestions on how to word it better

2022-09-21 18:04 UTC, rogeruiz requested changes
❌ This PR needs changes ...

Thanks @Shkeating for doing this work. I left some suggestions that need to be addressed and can be done via the GitHub UI if you'd like. But otherwise, this looks good and better than #2193

2022-09-21 18:04 UTC, rogeruiz commented on docs/for_trussels.md
> +- [ ] _Optional:_ Add yourself to the `contributors` list in the the [the README](../README.md), using the command `yarn contributors:add [your github username] code`
```suggestion
- [ ] _Optional:_ Add yourself to the `contributors` list in the [the README](../README.md), using the command `yarn contributors:add [your github username] code`
```

2022-09-21 18:04 UTC, rogeruiz commented on docs/for_trussels.md
> +- [ ] \_Optional: Add yourself to [CODEOWNERS](../CODEOWNERS) if you'd like to automatically be requested to review PRs.
```suggestion
- [ ] _Optional_: Add yourself to [CODEOWNERS](../CODEOWNERS) if you'd like to automatically be requested to review PRs.
```

2022-09-22 23:38 UTC, gidjin approved these changes
LGTM

2022-09-23 19:25 UTC, merged