fix (time Picker component): making label on TimePicker mandatory
trussworks/react-uswds pull request #2629
Opened 2023-10-15 04:02 UTC by m7adeel

# Summary
Resolved mandatory label prop requirement for the time picker component, enhancing compliance with USWDS documentation.

## Related Issues or PRs
Closes #2611

## How To Test
The developer can try to add a TimePicker component without a label prop which would result in a typescript error with a msg of (Property 'label' is missing)

### Screenshots 
![Screenshot from 2023-10-15 08-29-03](https://github.com/trussworks/react-uswds/assets/87698014/928c8ba6-efa3-4a18-b762-df1c54cbbfa5)
![Screenshot from 2023-10-15 08-27-25](https://github.com/trussworks/react-uswds/assets/87698014/2ee62290-a979-4f5d-b910-cd223006888b)
![Screenshot from 2023-10-15 08-27-05](https://github.com/trussworks/react-uswds/assets/87698014/544984e9-dd11-4172-8b9a-9a344784d231)
![Screenshot from 2023-10-15 08-26-54](https://github.com/trussworks/react-uswds/assets/87698014/4d004dab-39fa-48f0-8cdf-d2351dfa13be)

2023-10-16 07:51 UTC, m7adeel commented
Hello @shkeating, I have worked on this issue can you kindly review it?

2023-10-17 23:55 UTC, brandonlenz commented
@m7adeel please update the tests for TimePicker to include a label, now that label is mandatory on this branch tests are failing as a result

2023-10-17 23:56 UTC, brandonlenz commented
Updated title to `fix!` as this will be a breaking change, mandating a major version bump on the next release

2023-10-18 15:14 UTC, AnnaGingle submitted a review, later dismissed
Looks good to me! Great work. I do have some feedback on the PR instructions, particularly the how to test section. I humbly suggest adding a sentence or two about how the PR relates to the design of the component. It's a great way to get new design contributors in the door.

2023-10-18 15:33 UTC, brandonlenz commented on src/components/forms/TimePicker/TimePicker.stories.tsx
> +      label="Appointment Time"
USWDS' example uses sentence case for this label, we should match their example:

```suggestion
      label="Appointment time"
```

2023-10-20 03:04 UTC, AnnaGingle submitted a review, later dismissed
LGTM

2023-10-20 03:07 UTC, AnnaGingle commented
I did notice the time picker component label is using Start Case where it should be using sentence case.
-This Sentence Is Called A Start Case.
-This sentence is called a sentence case.
The [USWDS website](https://designsystem.digital.gov/components/time-picker/#component-code) uses sentence case & it’s better for accessibility.

2023-10-20 16:39 UTC, brandonlenz commented
Noticing the lockfiles got corrupted on this branch. Gonna try to resolve to move this along

2023-10-20 16:42 UTC, brandonlenz commented
> Noticing the lockfiles got corrupted on this branch. Gonna try to resolve to move this along

Ah right, I'd have to make a fork of your fork for those updates to display in github.

@m7adeel can you resolve the issues with the lock files? Looks like maybe an npm command was issued? 

My recommendation:
1. Delete package.lock.json (we use yarn on this project)
2. Revert any changes to yarn.lock. There should be no diff here as package.json was not changed. This PR includes code changes only

2023-10-21 13:01 UTC, m7adeel commented
@brandonlenz I have fixed the issues

2023-10-23 16:06 UTC, brandonlenz approved these changes, later dismissed

2023-10-23 21:00 UTC, AnnaGingle requested changes
I did notice the time picker component label is using Start Case where it should be using sentence case.
This Sentence Is Called A Start Case.
This sentence is called a sentence case.
The [USWDS website](https://designsystem.digital.gov/components/time-picker/#component-code) uses sentence case & it’s better for accessibility.

2023-10-25 01:59 UTC, brandonlenz commented
> I did notice the time picker component label is using Start Case where it should be using sentence case. This Sentence Is Called A Start Case. This sentence is called a sentence case. The [USWDS website](https://designsystem.digital.gov/components/time-picker/#component-code) uses sentence case & it’s better for accessibility.

@AnnaGingle I'm seeing this PR updated to sentence case. Can you confirm?

2023-10-25 20:45 UTC, brandonlenz approved these changes

2023-10-25 20:59 UTC, AnnaGingle approved these changes
Looks good to me!

2023-10-27 14:25 UTC, merged

2026-04-18 13:51 UTC, nmcconlogueOG commented
I feel like this fix goes in the wrong direction, a component library should make it easier for the developers to implement the spec correctly - not enforce it at the api level.   Making label mandatory on TimePicker creates an inconsistency with DatePicker, which leaves label ownership to the consumer. This matters when using TimePicker inside a form library like RJSF with custom field templates —   the template owns the label rendering and positions it alongside hint text in the correct DOM order (label -> hint ->input). With a required label prop, TimePicker renders its own label internally, which you can't opt out of, so you end up with duplicate labels unless you pass an empty string — which is a hack that breaks accessibility. DatePicker avoids this entirely by not having a label prop, letting the consumer render it  externally. TimePicker should follow the same pattern, or at minimum make label optional so consumers can  suppress it when their layout owns the labeling.